@echo off
echo Moving components...
robocopy components src\components /E /MOVE /NFL /NDL /NJH /NJS /NP
echo Moving utils...
robocopy utils src\utils /E /MOVE /NFL /NDL /NJH /NJS /NP
echo Moving hooks...
robocopy hooks src\hooks /E /MOVE /NFL /NDL /NJH /NJS /NP
echo Moving app libs...
robocopy app\lib src\lib /E /MOVE /NFL /NDL /NJH /NJS /NP
robocopy app\redux src\redux /E /MOVE /NFL /NDL /NJH /NJS /NP
robocopy app\services src\services /E /MOVE /NFL /NDL /NJH /NJS /NP
echo Moving rest of app...
robocopy app src\app /E /MOVE /NFL /NDL /NJH /NJS /NP
echo Migration Complete.

