import { userRoleEnums } from "@/services/local/local.const";
import {
  LayoutDashboard,
  LogOut,
  Projector,
  Settings,
  User,
  Activity,
  HelpCircle,
  Users2,
  BarChart3,
  Inbox,
  HardDrive,
  Code2,
  ShieldAlert,
  Puzzle,
  Map,
  Gift,
  ActivitySquare,
  CheckSquare,
  LayoutTemplate,
  History,
  Bell,
  Rocket,
  Calendar,
  FileText,
  MessageSquare,
} from "lucide-react";

// export const getPagePath = (path: string, role: string) => {
//   for (const pageKey in pagesInfo) {
//     const page = pagesInfo[pageKey as keyof typeof pagesInfo];

//     if (page.regex.test(path) && page.role.includes(role)) {
//       return page;
//     }

//     if (page?.child) {
//       for (const childKey in page?.child) {
//         const child = page?.child[childKey];
//         if (child.regex.test(path) && child.role.includes(role)) {
//           return child;
//         }
//       }
//     }
//   }

//   return null;
// };

export const getPath = (
  path: string,
  params: Record<string, string | number>,
): string => {
  return Object.keys(params).reduce((updatedPath, key) => {
    const placeholder = `:${key}`;
    return updatedPath.replace(placeholder, String(params[key]));
  }, path);
};

export const isPathMatch = (regexList: RegExp[], path: string): boolean =>
  regexList.some((regex) => regex.test(path));

export const pagesInfo = {
  // public pages
  home: {
    key: "home",
    label: "Home",
    path: "/",
    regex: /^\/$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  login: {
    key: "login",
    label: "Login",
    path: "/login",
    regex: /^\/login$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },
  privacy: {
    key: "privacy",
    label: "Privacy",
    path: "/privacy",
    regex: /^\/privacy$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },
  terms: {
    key: "terms",
    label: "Terms",
    path: "/terms",
    regex: /^\/terms$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },
  data_deletion: {
    key: "data_deletion",
    label: "Data Deletion",
    path: "/data_deletion",
    regex: /^\/data_deletion$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },
  unauthorized: {
    key: "unauthorized",
    label: "Unauthorized",
    path: "/unauthorized",
    regex: /^\/unauthorized$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },

  // private pages
  dashboard: {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    regex: /^\/dashboard$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  projects: {
    key: "projects",
    label: "Projects",
    path: "/projects",
    regex: /^\/projects$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  team: {
    key: "team",
    label: "Team",
    path: "/team",
    regex: /^\/team$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  activity_log: {
    key: "activity_log",
    label: "Activity",
    path: "/activity",
    regex: /^\/activity$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  help_center: {
    key: "help_center",
    label: "Help Center",
    path: "/help",
    regex: /^\/help$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {
      documentation: {
        key: "documentation",
        label: "Documentation",
        path: "/help/documentation",
        regex: /^\/help\/documentation$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      faqs: {
        key: "faqs",
        label: "FAQs",
        path: "/help/faqs",
        regex: /^\/help\/faqs$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      contact: {
        key: "contact",
        label: "Contact",
        path: "/help/contact",
        regex: /^\/help\/contact$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      article_reader: {
        key: "article_reader",
        label: "Article Reader",
        path: "/help/article/:slug",
        regex: /^\/help\/article\/.*$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
    },
  },
  reports: {
    key: "reports",
    label: "Reports",
    path: "/reports",
    regex: /^\/reports$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  inbox: {
    key: "inbox",
    label: "Inbox",
    path: "/inbox",
    regex: /^\/inbox$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  storage: {
    key: "storage",
    label: "Storage",
    path: "/storage",
    regex: /^\/storage$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  developers_portal: {
    key: "developers_portal",
    label: "Developers",
    path: "/developers",
    regex: /^\/developers$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  audit_logs: {
    key: "audit_logs",
    label: "Audit Logs",
    path: "/audit",
    regex: /^\/audit$/,
    role: [userRoleEnums.admin.value],
    child: {},
  },
  marketplace: {
    key: "marketplace",
    label: "Marketplace",
    path: "/marketplace",
    regex: /^\/marketplace$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  roadmap: {
    key: "roadmap",
    label: "Roadmap",
    path: "/roadmap",
    regex: /^\/roadmap$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  referrals: {
    key: "referrals",
    label: "Referrals",
    path: "/referrals",
    regex: /^\/referrals$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  status: {
    key: "status",
    label: "System Status",
    path: "/status",
    regex: /^\/status$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  tasks: {
    key: "tasks",
    label: "My Tasks",
    path: "/tasks",
    regex: /^\/tasks$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  templates: {
    key: "templates",
    label: "Templates",
    path: "/templates",
    regex: /^\/templates$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  changelog: {
    key: "changelog",
    label: "Changelog",
    path: "/changelog",
    regex: /^\/changelog$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  notifications: {
    key: "notifications",
    label: "Notifications",
    path: "/notifications",
    regex: /^\/notifications$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  onboarding: {
    key: "onboarding",
    label: "Getting Started",
    path: "/onboarding",
    regex: /^\/onboarding$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  calendar: {
    key: "calendar",
    label: "Calendar",
    path: "/calendar",
    regex: /^\/calendar$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  documents: {
    key: "documents",
    label: "Documents",
    path: "/documents",
    regex: /^\/documents$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {},
  },
  feedback: {
    key: "feedback",
    label: "Feedback",
    path: "/feedback",
    regex: /^\/feedback$/,
    role: [userRoleEnums.admin.value, userRoleEnums.company.value],
    child: {},
  },
  settings: {
    key: "settings",
    label: "Settings",
    path: "/settings",
    regex: /^\/settings$/,
    role: [
      userRoleEnums.admin.value,
      userRoleEnums.company.value,
      userRoleEnums.employee.value,
    ],
    child: {
      company: {
        key: "company",
        label: "Company",
        path: "/settings/company",
        regex: /^\/settings\/company$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      integrations: {
        key: "integrations",
        label: "Integrations",
        path: "/settings/integrations",
        regex: /^\/settings\/integrations$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      subscription: {
        key: "subscription",
        label: "Subscription",
        path: "/settings/subscription",
        regex: /^\/settings\/subscription$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      security: {
        key: "security",
        label: "Security",
        path: "/settings/security",
        regex: /^\/settings\/security$/,
        role: [userRoleEnums.admin.value, userRoleEnums.company.value],
        child: {},
      },
      organization: {
        key: "organization",
        label: "Organization",
        path: "/settings/organization",
        regex: /^\/settings\/organization$/,
        role: [userRoleEnums.admin.value, userRoleEnums.company.value],
        child: {},
      },
      billing: {
        key: "billing",
        label: "Billing",
        path: "/settings/billing",
        regex: /^\/settings\/billing$/,
        role: [userRoleEnums.admin.value, userRoleEnums.company.value],
        child: {},
      },
      developers: {
        key: "developers",
        label: "Developers",
        path: "/settings/developers",
        regex: /^\/settings\/developers$/,
        role: [userRoleEnums.admin.value, userRoleEnums.company.value],
        child: {},
      },
      notifications: {
        key: "notifications",
        label: "Notifications",
        path: "/settings/notifications",
        regex: /^\/settings\/notifications$/,
        role: [userRoleEnums.admin.value, userRoleEnums.company.value],
        child: {},
      },
      theme: {
        key: "theme",
        label: "Theme",
        path: "/settings/theme",
        regex: /^\/settings\/theme$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      region: {
        key: "region",
        label: "Region",
        path: "/settings/region",
        regex: /^\/settings\/region$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      compliance: {
        key: "compliance",
        label: "Compliance",
        path: "/settings/compliance",
        regex: /^\/settings\/compliance$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
      roles: {
        key: "roles",
        label: "Roles",
        path: "/settings/roles",
        regex: /^\/settings\/roles$/,
        role: [
          userRoleEnums.admin.value,
          userRoleEnums.company.value,
          userRoleEnums.employee.value,
        ],
        child: {},
      },
    },
  },
  logout: {
    key: "logout",
    label: "Logout",
    path: "/logout",
    regex: /^\/logout$/,
    role: Object.values(userRoleEnums).map((role) => role.value),
    child: {},
  },
};

export const navbarPages = [
  pagesInfo.dashboard.regex,
  pagesInfo.projects.regex,
  pagesInfo.settings.regex,
];

export const sidebarPages = [
  pagesInfo.dashboard.regex,
  pagesInfo.projects.regex,
  pagesInfo.settings.regex,
];

export const sidebarNavLinkConsts = {
  dashboard: {
    key: "dashboard",
    label: "Dashboard",
    iconUrl: "/sidebar/dashboard.svg",
    icon: LayoutDashboard,
    path: pagesInfo.dashboard.path,
    tooltip: "Dashboard",
  },
  projects: {
    key: "projects",
    label: "Projects",
    iconUrl: "/sidebar/projects.svg",
    icon: Projector,
    path: pagesInfo.projects.path,
    tooltip: "Projects",
  },
  team: {
    key: "team",
    label: "Team",
    iconUrl: "/sidebar/team.svg",
    icon: Users2,
    path: pagesInfo.team.path,
    tooltip: "Team Members",
  },
  activity_log: {
    key: "activity_log",
    label: "Activity",
    iconUrl: "/sidebar/activity.svg",
    icon: Activity,
    path: pagesInfo.activity_log.path,
    tooltip: "Activity Log",
  },
  help_center: {
    key: "help_center",
    label: "Help",
    iconUrl: "/sidebar/help.svg",
    icon: HelpCircle,
    path: pagesInfo.help_center.path,
    tooltip: "Help Center",
  },
  reports: {
    key: "reports",
    label: "Reports",
    iconUrl: "/sidebar/reports.svg",
    icon: BarChart3,
    path: pagesInfo.reports.path,
    tooltip: "Reports",
  },
  inbox: {
    key: "inbox",
    label: "Inbox",
    iconUrl: "/sidebar/inbox.svg",
    icon: Inbox,
    path: pagesInfo.inbox.path,
    tooltip: "Inbox",
  },
  storage: {
    key: "storage",
    label: "Storage",
    iconUrl: "/sidebar/storage.svg",
    icon: HardDrive,
    path: pagesInfo.storage.path,
    tooltip: "Storage",
  },
  developers_portal: {
    key: "developers_portal",
    label: "Developers",
    iconUrl: "/sidebar/code.svg",
    icon: Code2,
    path: pagesInfo.developers_portal.path,
    tooltip: "Developers",
  },
  audit_logs: {
    key: "audit_logs",
    label: "Audit Logs",
    iconUrl: "/sidebar/shield.svg",
    icon: ShieldAlert,
    path: pagesInfo.audit_logs.path,
    tooltip: "Audit Logs",
  },
  marketplace: {
    key: "marketplace",
    label: "Marketplace",
    iconUrl: "/sidebar/puzzle.svg",
    icon: Puzzle,
    path: pagesInfo.marketplace.path,
    tooltip: "Marketplace",
  },
  roadmap: {
    key: "roadmap",
    label: "Roadmap",
    iconUrl: "/sidebar/map.svg",
    icon: Map,
    path: pagesInfo.roadmap.path,
    tooltip: "Roadmap",
  },
  referrals: {
    key: "referrals",
    label: "Referrals",
    iconUrl: "/sidebar/gift.svg",
    icon: Gift,
    path: pagesInfo.referrals.path,
    tooltip: "Referrals",
  },
  status: {
    key: "status",
    label: "Status",
    iconUrl: "/sidebar/server.svg",
    icon: ActivitySquare,
    path: pagesInfo.status.path,
    tooltip: "System Status",
  },
  tasks: {
    key: "tasks",
    label: "My Tasks",
    iconUrl: "/sidebar/check.svg",
    icon: CheckSquare,
    path: pagesInfo.tasks.path,
    tooltip: "My Tasks",
  },
  templates: {
    key: "templates",
    label: "Templates",
    iconUrl: "/sidebar/template.svg",
    icon: LayoutTemplate,
    path: pagesInfo.templates.path,
    tooltip: "Templates",
  },
  changelog: {
    key: "changelog",
    label: "Changelog",
    iconUrl: "/sidebar/history.svg",
    icon: History,
    path: pagesInfo.changelog.path,
    tooltip: "Changelog",
  },
  notifications: {
    key: "notifications",
    label: "Notifications",
    iconUrl: "/sidebar/bell.svg",
    icon: Bell,
    path: pagesInfo.notifications.path,
    tooltip: "Notifications",
  },
  onboarding: {
    key: "onboarding",
    label: "Get Started",
    iconUrl: "/sidebar/rocket.svg",
    icon: Rocket,
    path: pagesInfo.onboarding.path,
    tooltip: "Onboarding",
  },
  calendar: {
    key: "calendar",
    label: "Calendar",
    iconUrl: "/sidebar/calendar.svg",
    icon: Calendar,
    path: pagesInfo.calendar.path,
    tooltip: "Calendar",
  },
  documents: {
    key: "documents",
    label: "Documents",
    iconUrl: "/sidebar/document.svg",
    icon: FileText,
    path: pagesInfo.documents.path,
    tooltip: "Documents",
  },
  feedback: {
    key: "feedback",
    label: "Feedback",
    iconUrl: "/sidebar/message.svg",
    icon: MessageSquare,
    path: pagesInfo.feedback.path,
    tooltip: "Feedback",
  },
  settings: {
    key: "settings",
    label: "Settings",
    iconUrl: "/sidebar/settings.svg",
    icon: Settings,
    path: pagesInfo.settings.path,
    tooltip: "Settings",
  },
  logout: {
    key: "logout",
    label: "Logout",
    iconUrl: "/sidebar/logout.svg",
    icon: LogOut,
    path: pagesInfo.logout.path,
    tooltip: "Logout",
  },
};

export const publicPages: string[] = [
  pagesInfo.home.path,
  pagesInfo.login.path,
  pagesInfo.privacy.path,
  pagesInfo.terms.path,
  pagesInfo.data_deletion.path,
  pagesInfo.unauthorized.path,
];
